"""Live probe of the case-generation path; writes a sanitized report only.

Runs the same code the poller runs (Gemini cascade -> create_case -> validate_case)
against the real GEMINI_API key, captures only the safe diagnostics lines that the
logging layer already guarantees: no keys, prompts, answers, case text or truth.

Usage: python scripts/ai_probe.py   (env GEMINI_API required; PROBE_REPORT optional)
"""

import asyncio
import logging
import os
import sys
import time
from pathlib import Path

# Allow `python scripts/ai_probe.py` from a checkout root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ai.gemini import AIUnavailable, Gemini, cause
from ai.host import create_case
from game.rules import role_specs

REPORT = os.getenv("PROBE_REPORT", "diagnostics/last-ai-probe.md")
# Mirrors Court.start: the poller gives the generator 60 seconds.
CASE_TIMEOUT = 60


class Capture(logging.Handler):
    """Keeps formatted log lines that are safe by construction (see README)."""

    def __init__(self):
        super().__init__()
        self.lines = []

    def emit(self, record):
        self.lines.append(self.format(record))


async def main():
    capture = Capture()
    capture.setFormatter(logging.Formatter("%(name)s %(levelname)s %(message)s"))
    logging.basicConfig(level=logging.INFO, handlers=[capture])
    logging.getLogger("httpx").setLevel(logging.WARNING)
    logging.getLogger("aiogram").setLevel(logging.WARNING)

    keys = [k.strip() for k in os.environ.get("GEMINI_API", "").split(",") if k.strip()]
    started = time.monotonic()
    log = logging.getLogger("court.probe")
    log.info(
        "Probe start keys_configured=%d models=%s case_timeout=%ds",
        len(keys),
        ",".join(Gemini.models),
        CASE_TIMEOUT,
    )
    # Exactly the call the poller makes for a 9-role table (see game/service.py).
    codes = [spec[0] for spec in role_specs(9)]
    previous = [
        "Кража экспоната из музея",
        "Отравление на банкете",
        "Поджог склада",
    ]
    result = "failed"
    try:
        ai = Gemini(os.environ.get("GEMINI_API", ""))
        try:
            async with asyncio.timeout(CASE_TIMEOUT):
                case = await create_case(ai, codes, previous)
            # Only structural facts about the answer; never its text or truth.
            log.info(
                "Probe case accepted evidence=%d roles_required=%d crime_chars=%d",
                len(case["evidence"]),
                len(codes),
                len(case["crime"]),
            )
            result = "accepted"
        except AIUnavailable as exc:
            log.error("Probe case failed reason=%s", cause(exc))
        except TimeoutError:
            log.error("Probe case failed reason=TimeoutError after %ds", CASE_TIMEOUT)
        finally:
            await ai.close()
    except Exception as exc:  # noqa: BLE001 — the probe must always produce a report
        log.error("Probe crashed reason=%s", cause(exc))

    log.info("Probe done result=%s elapsed=%.1fs", result, time.monotonic() - started)
    return [
        "# AI probe report (sanitized)",
        "",
        "Generated by `scripts/ai_probe.py` via `.github/workflows/diagnostics.yml`.",
        "Keys, prompts, answers, case text and truth are never logged or stored.",
        "",
        f"- keys configured: {len(keys)}",
        f"- models: {', '.join(Gemini.models)}",
        f"- create_case timeout: {CASE_TIMEOUT}s (same as the poller)",
        f"- result: {result}",
        "",
        "## Probe log lines",
        "",
        "```",
        *capture.lines,
        "```",
        "",
    ]


def write_report(lines):
    path = Path(REPORT)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    write_report(asyncio.run(main()))
